# .pre-commit-config.yaml
# ========================
#
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# precommit hooks installation
#
# - pre-commit autoupdate
#
#
# continuous integration
# ======================
#
# - pre-commit run --all-files
#

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: trailing-whitespace
        exclude: |
          (?x)(
              ^.git/ |
              ^.github/ |
              ^.frontend/ |
              ^.git/ |
              ^__pycache__/ |
              ^__init__.py/ |
              ^.mypy_cache/ |
              ^.pytest_cache/ |
              ^.venv*/ |
              ^.tox/ |
              ^.idea/ |
              ^output/ |
              ^input/
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              ^.git/ |
              ^.github/ |
              ^.frontend/ |
              ^.git/ |
              ^__pycache__/ |
              ^__init__.py/ |
              ^.mypy_cache/ |
              ^.pytest_cache/ |
              ^.venv*/ |
              ^.tox/ |
              ^.idea/ |
              ^output/ |
              ^input/
          )
      - id: check-yaml
        exclude: |
          (?x)(
              ^.git/ |
              ^.github/ |
              ^.frontend/ |
              ^.git/ |
              ^__pycache__/ |
              ^__init__.py/ |
              ^.mypy_cache/ |
              ^.pytest_cache/ |
              ^.venv*/ |
              ^.tox/ |
              ^.idea/ |
              ^output/ |
              ^input/
          )
      - id: check-json
        exclude: |
          (?x)(
              ^.git/ |
              ^.github/ |
              ^.frontend/ |
              ^.git/ |
              ^__pycache__/ |
              ^__init__.py/ |
              ^.mypy_cache/ |
              ^.pytest_cache/ |
              ^.venv*/ |
              ^.tox/ |
              ^.idea/ |
              ^output/ |
              ^input/
          )
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
        description: Forces to replace line ending by the UNIX 'lf' character.
        exclude: |
          (?x)(
              ^.git/ |
              ^.github/ |
              ^.frontend/ |
              ^.git/ |
              ^__pycache__/ |
              ^__init__.py/ |
              ^.mypy_cache/ |
              ^.pytest_cache/ |
              ^.venv*/ |
              ^.tox/ |
              ^.idea/ |
              ^output/ |
              ^input/
          )
      - id: pretty-format-json
        args: [ '--no-sort-keys' ]
        exclude: |
          (?x)(
              ^.git/ |
              ^.github/ |
              ^.frontend/ |
              ^.git/ |
              ^__pycache__/ |
              ^__init__.py/ |
              ^.mypy_cache/ |
              ^.pytest_cache/ |
              ^.venv*/ |
              ^.tox/ |
              ^.idea/ |
              ^output/ |
              ^input/
          )
      - id: no-commit-to-branch
        args: [ --branch, main ]
        exclude: |
          (?x)(
              ^.git/ |
              ^.github/ |
              ^.frontend/ |
              ^.git/ |
              ^__pycache__/ |
              ^__init__.py/ |
              ^.mypy_cache/ |
              ^.pytest_cache/ |
              ^.venv*/ |
              ^.tox/ |
              ^.idea/ |
              ^output/ |
              ^input/
          )
        minimum_pre_commit_version: '2.9.2'
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        args: [ --line-length=79 ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=102, --format=pylint, -jobs=auto]
        exclude: ^.venv*|venv*|.git|__pycache__|__init__.py|.mypy_cache|.pytest_cache|alembic|.venv|.tox|.idea|.venv310|.env|.venv|input|output
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies:
          - types-PyYAML
